In [1]:
%reload_ext autoreload
%autoreload 2

# Imports

In [2]:
from kret_notebook import *  # NOTE import first
from kret_lgbm._core.lgbm_nb_imports import *
from kret_lightning._core.lightning_nb_imports import *
from kret_matplotlib._core.mpl_nb_imports import *
from kret_np_pd._core.np_pd_nb_imports import *
from kret_optuna._core.optuna_nb_imports import *
from kret_polars._core.polars_nb_imports import *
from kret_rosetta._core.rosetta_nb_imports import *
from kret_sklearn._core.sklearn_nb_imports import *
from kret_torch_utils._core.torch_nb_imports import *
from kret_tqdm._core.tqdm_nb_imports import *
from kret_type_hints._core.types_nb_imports import *
from kret_utils._core.utils_nb_imports import *

# from kret_wandb._core.wandb_nb_imports import *  # NOTE this is slow to import

Loaded environment variables from /Users/Akseldkw/coding/kretsinger/.env
[kret_lgbm._core.lgbm_nb_imports] Imported kret_lgbm._core.lgbm_nb_imports in 2.1606 seconds
[kret_lightning._core.lightning_nb_imports] Imported kret_lightning._core.lightning_nb_imports in 4.4798 seconds
[kret_matplotlib._core.mpl_nb_imports] Imported kret_matplotlib._core.mpl_nb_imports in 0.2782 seconds
[kret_np_pd._core.np_pd_nb_imports] Imported kret_np_pd._core.np_pd_nb_imports in 0.0005 seconds
[kret_optuna._core.optuna_nb_imports] Imported kret_optuna._core.optuna_nb_imports in 0.0015 seconds
[kret_polars._core.polars_nb_imports] Imported kret_polars._core.polars_nb_imports in 0.1123 seconds
[kret_rosetta._core.rosetta_nb_imports] Imported kret_rosetta._core.rosetta_nb_imports in 0.0000 seconds
[kret_sklearn._core.sklearn_nb_imports] Imported kret_sklearn._core.sklearn_nb_imports in 0.1947 seconds
[kret_torch_utils._core.torch_nb_imports] Imported kret_torch_utils._core.torch_nb_imports in 0.4228 seconds
[kret_tqdm._core.tqdm_nb_imports] Imported kret_tqdm._core.tqdm_nb_imports in 0.0002 seconds
[kret_type_hints._core.types_nb_imports] Imported kret_type_hints._core.types_nb_imports in 0.0009 seconds
[kret_utils._core.utils_nb_imports] Imported kret_utils._core.utils_nb_imports in 0.0011 seconds

# Implementation

In [3]:
out = UTILS_sklearn.make_regression()

In [4]:
out_multi = UTILS_sklearn.make_multilabel_classification()

In [5]:
isinstance(out_multi, tuple)

True

In [6]:
UKS_NP_PD.dtt(out_multi, show_dims=True, titles=["X_multi", "y_multi", "1", "2"])

In [7]:
str_arr = np.array(
    [
        "L2ndFloor-D-2022-01-24_T-14_30_02",
        "L2ndFloor-D-2022-01-31_T-14_30_02",
        "L2ndFloor-D-2021-12-25_T-14_00_01",
        "L2ndFloor-D-2021-12-25_T-18_30_01",
        "L2ndFloor-D-2022-03-14_T-18_00_01",
    ],
    dtype="<U33",
)

In [8]:
UKS_NP_PD.dtt([str_arr], titles=["str_arr"], show_dims=True, max_col_width=250)

In [21]:
styler = UKS_MPL.heatmap_styler(out_multi.x, cmap="Reds")
# styler

In [ ]:
UKS_NP_PD.dtt([styler, out_multi.x], titles=["styler", "data"], how="head")

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,3.0,0.0,4.0,2.0,5.0,1.0,3.0,9.0,2.0,6.0,3.0,0.0,0.0,5.0,0.0,3.0
1,6.0,1.0,7.0,4.0,2.0,3.0,4.0,2.0,3.0,3.0,2.0,2.0,4.0,5.0,1.0,5.0
2,3.0,5.0,4.0,5.0,5.0,1.0,5.0,3.0,1.0,2.0,2.0,1.0,3.0,5.0,1.0,3.0
3,4.0,5.0,4.0,5.0,4.0,1.0,3.0,4.0,4.0,1.0,2.0,0.0,2.0,8.0,0.0,7.0
4,4.0,3.0,1.0,5.0,5.0,1.0,6.0,2.0,3.0,7.0,0.0,1.0,3.0,3.0,1.0,1.0
,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64
0,3.000,0.000,4.000,2.000,5.000,1.000,3.000,9.000,2.000,6.000,3.000,0.000,0.000,5.000,0.000,3.000
1,6.000,1.000,7.000,4.000,2.000,3.000,4.000,2.000,3.000,3.000,2.000,2.000,4.000,5.000,1.000,5.000
2,3.000,5.000,4.000,5.000,5.000,1.000,5.000,3.000,1.000,2.000,2.000,1.000,3.000,5.000,1.000,3.000
3,4.000,5.000,4.000,5.000,4.000,1.000,3.000,4.000,4.000,1.000,2.000,0.000,2.000,8.000,0.000,7.000
4,4.000,3.000,1.000,5.000,5.000,1.000,6.000,2.000,3.000,7.000,0.000,1.000,3.000,3.000,1.000,1.000